language: node_js
node_js:
  - 14
addons:
  packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - npm run test:ci
  - npm run test:cypress:ci
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: clean-architecture-react
  skip_cleanup: true
notifications:
  email: false